### ISSUE TITLE
Add support for Xcode 14 / Swift 5.7

### ISSUE THREAD

**Issue by maniramezan** [awslabs/smithy-swift#415]
## Warning ##
* You should only be opening a feature request in this repository if it pertains to **non-AWS specific features pertaining to code generation of an SDK.**
* **If you have feature request pertaining to the AWS SDK for Swift**, please open it in:
    * https://github.com/awslabs/aws-sdk-swift/blob/main/.github/ISSUE_TEMPLATE/feature_request.md

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

With today's release of Xcode 14 and at the moment, no available Xcode stable version on macOS Ventura, it'd be nice if we remove the check for Swift 5.7 and add that version as a supported version to `swiftVersion` in `SwiftVersion.swift`.

## Is your Feature Request related to a problem?

Yes, compiler errors when using Xcode 14.

## Proposed Solution

Adding Swift 5.7 to the list of supported versions.

## Describe alternatives you've considered

Don't use beta version of Xcode

## Additional Context

- [X] I may be able to implement this feature request

**Comment by atierian** [comment]
Thanks for opening this feature request @maniramezan. I agree this should be added.

I see you mentioned in the feature request that you may be able to implement this yourself. You can check out the change made a few months ago to support Swift 5.6 (yes that's really all that's needed 🙂).

Feel free to open a PR for this if you'd like to. If not, no problem, I'll take care of it. 

Let me know if you have any questions.

**Comment by maniramezan** [comment]
@atierian Yeah sure sounds good, I can take care of it. For the next version of Swift, since it's still unclear what'd be the next Swift version, I think it'd make sense to go with 5.8 and if Apple goes straight to 6, that can be updated later to just reduce the confusion for anybody reading the error later on

**Comment by maniramezan** [comment]
For the time being, I created the [PR](https://github.com/awslabs/smithy-swift/pull/416). Followed the same steps as the previous one. Thanks again for being open for adding this change now and letting me do it.

**Comment by atierian** [comment]
Thanks for the contribution @maniramezan!
It was included in [0.2.4](https://github.com/awslabs/smithy-swift/releases/tag/0.2.4)
