### ISSUE TITLE
Add support for Xcode 14.3.1 / Swift 5.8.1 

### ISSUE THREAD

**Issue by SPConrad** [awslabs/smithy-swift#572]
### Describe the feature

The latest version of Xcode, 14.3.1, supports up to Swift 5.8.1. Projects dependent on these versions are unable to use `smithy-swift`. 

### Use Case

Any Swift or iOS features which require Xcode 14.3 or 14.3.1, or Swift 5.8 or 5.8.1 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Closing this issue.  Feel free to reopen & clarify your request if you are still having problems with this project on latest Xcode.
